# Generated by Django 4.2.4 on 2023-08-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_manga'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('image', models.ImageField(upload_to='manga_images/')),
            ],
        ),
    ]
