# Generated by Django 4.2.4 on 2023-08-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_mangalist'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangalist',
            name='manga_id',
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
    ]
